version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: mongo:3.4
    steps:
      - checkout
      - restore_cache:
          key: squadmanager-gradle4-{{ .Branch }}
      - type: shell
        command: ./gradlew vendor
      - save_cache:
          key: squadmanager-gradle4-{{ .Branch }}
          paths:
            - ~/.gradle
            - .gogradle/project_gopath
      - run:
          name: Run unit tests
          command: ./gradlew test
      - store_artifacts:
          path: .gogradle/reports/test
      - store_test_results:
          path: .gogradle/reports/test
